name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as per your project's dependencies

    - name: Build
      run: |
        # Add build commands here if needed
        echo "Build commands go here"

    - name: Run tests
      run: |
        # Add test commands here
        python -m unittest discover tests/  # Adjust as per your test structure

    - name: Mutation testing
      run: |
        # Add mutation testing commands here
        # Example using mutmut
        pip install mutmut
        mutmut run

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/
