name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: |
        npm install

    - name: Set up Babel
      run: |
        npm install --save-dev @babel/core @babel/node @babel/preset-env @babel/register

    - name: Set up Istanbul (nyc)
      run: |
        npm install --save-dev nyc

    - name: Set up Stryker
      run: |
        npm install --save-dev @stryker-mutator/core @stryker-mutator/jest-runner @stryker-mutator/karma-runner @stryker-mutator/mocha-runner

    - name: Set up Jest
      run: |
        npm install --save-dev jest

    - name: Set up Mocha
      run: |
        npm install --save-dev mocha

    - name: Set up Chai
      run: |
        npm install --save-dev chai chai-as-promised chai-http sinon-chai

    - name: Set up Sinon
      run: |
        npm install --save-dev sinon

    - name: Set up Nock
      run: |
        npm install --save-dev nock

    - name: Set up Stryker CLI
      run: |
        npm install --save-dev stryker-cli

    - name: Set up ESM
      run: |
        npm install --save-dev esm

    - name: Set up Istanbul (global)
      run: |
        npm install -g istanbul

    - name: Set up Sequelize
      run: |
        npm install --save-dev sequelize sequelize-cli mysql2

    - name: Set up Firebase
      run: |
        npm install --save-dev firebase

    - name: Set up Paginationjs
      run: |
        npm install --save-dev paginationjs

    - name: Set up Dotenv
      run: |
        npm install --save-dev dotenv

    - name: Set up Cors
      run: |
        npm install --save-dev cors

    - name: Set up Body Parser
      run: |
        npm install --save-dev body-parser

    - name: Set up UUID
      run: |
        npm install --save-dev uuid

    - name: Set up Multer
      run: |
        npm install --save-dev multer

    - name: Set up Express
      run: |
        npm install --save-dev express express-ejs-layouts

    - name: Set up JWT
      run: |
        npm install --save-dev jsonwebtoken

    - name: Set up Chai as Promised
      run: |
        npm install --save-dev chai-as-promised

    - name: Set up EJS
      run: |
        npm install --save-dev ejs

    - name: Set up Sinon Chai
      run: |
        npm install --save-dev sinon-chai

    - name: Set up Karma Runner for Stryker (if needed)
      run: |
        npm install --save-dev @stryker-mutator/karma-runner

    - name: Set up Mocha Runner for Stryker (if needed)
      run: |
        npm install --save-dev @stryker-mutator/mocha-runner

    - name: Build
      run: |
        # Add build commands here if needed
        echo "Build commands go here"

    - name: Run tests
      run: |
        npm test

    - name: Mutation testing
      run: |
        # Ensure Stryker is configured properly before running this command
        npx stryker
